DROP TABLE PRODUCT_CATEGORY;
DROP TABLE CATEGORIES;
DROP TABLE PICTURES;
DROP TABLE FOLLOWINGS;
DROP TABLE PRODUCTS;
DROP TABLE USERS;

DROP SEQUENCE USER_ID_S;
DROP SEQUENCE PRODUCT_ID_S;
DROP SEQUENCE FOLLOWING_ID_S;
DROP SEQUENCE CATEGORY_ID_S;

CREATE SEQUENCE USER_ID_S START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE PRODUCT_ID_S START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE FOLLOWING_ID_S START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE SEQUENCE CATEGORY_ID_S START WITH 1 INCREMENT BY 1 NOMAXVALUE;

CREATE TABLE USERS 
(
  ID INT NOT NULL PRIMARY KEY,
  LOGIN VARCHAR2(30) NOT NULL UNIQUE,
  PASSWORD VARCHAR2(128) NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  SECOND_NAME VARCHAR2(50) NOT NULL,
  BIRTH DATE NOT NULL,
  EMAIL VARCHAR2(50) NOT NULL UNIQUE,
  PHONE VARCHAR2(20),
  REGISTRATION_DATE DATE NOT NULL,
  STATUS VARCHAR2(64) CHECK (STATUS IN ('user', 'admin', 'unactivated', 'banned')) NOT NULL
);

CREATE TABLE PRODUCTS
(
  ID INT NOT NULL PRIMARY KEY,
  SELLER_ID INT NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(1500),
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  START_PRICE NUMBER NOT NULL,
  BUYOUT_PRICE NUMBER,
  CURRENT_PRICE NUMBER,
  CURRENT_BUYER_ID INT,
  IS_ACTIVE VARCHAR2(10) CHECK (IS_ACTIVE IN ('active', 'disactive')),
  CONSTRAINT SELLER_FK FOREIGN KEY(SELLER_ID) REFERENCES USERS(ID),
  CONSTRAINT BUYER_FK FOREIGN KEY(CURRENT_BUYER_ID) REFERENCES USERS(ID)
);

CREATE TABLE FOLLOWINGS 
(
  ID INT NOT NULL PRIMARY KEY,
  FOLLOWER_ID INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  CONSTRAINT FOLLOWER_FK FOREIGN KEY(FOLLOWER_ID) REFERENCES USERS(ID),
  CONSTRAINT PRODUCT_FK FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

CREATE TABLE PICTURES 
(
  PRODUCT_ID INT NOT NULL,
  URL VARCHAR2(100) NOT NULL,
  CONSTRAINT PRODUCT_PIC_FK FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

CREATE TABLE CATEGORIES 
(
  ID INT NOT NULL PRIMARY KEY,
  PARENT_ID INT,
  NAME VARCHAR2(100) NOT NULL,
  CONSTRAINT PARENT_CATEGORY_FK FOREIGN KEY(PARENT_ID) REFERENCES CATEGORIES(ID)
);

CREATE TABLE PRODUCT_CATEGORY
(
  PRODUCT_ID INT NOT NULL,
  CATEGORY_ID INT NOT NULL,
  CONSTRAINT PRODUCT_ID_FK FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID),
  CONSTRAINT CATEGORY_ID_FK FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES(ID)
);

commit;